# Generated by Django 5.0.7 on 2024-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_key", "0002_alter_apikey_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
